name: qa

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint

  build:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 18
          - 20
          - 22
          - 23
        architecture:
          - x64
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: install dependencies
        run: npm ci
      - name: run build
        run: npm run build
      - name: run test
        run: npm test
